name: Package Application with Pyinstaller

on:
  
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@python3.10    
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: duplicate-finder
        path: src/dist/linux

